version: "2"
services:
    client:
        image: mhart/alpine-node:10.23
        restart: always
        ports:
            - "3000:3000"
        working_dir: /client/src/app
        volumes:
            - ./client:/client/src/app
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            - webappnetwork
    api:
        image: ignaciods/webapp-api:20210220
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=productListUser
            - MONGO_INITDB_ROOT_PASSWORD=productListPassword
            - MONGO_INITDB_DATABASE=admin
        volumes:
            - ./data-node:/data/db
            - ./database:/database
        ports:
            - 27017:27017
        command: mongod 
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
